name: mmcalendar
description: "Myanmar Calendar Application"
publish_to: 'none'
version: 2.0.0+202
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  core:
    path: ../../packages/core
  data:
    path: ../../packages/data
  localizations:
    path: ../../packages/localizations

  # Features
  calendar:
    path: ../../packages/features/calendar
  settings:
    path: ../../packages/features/settings
  views:
    path: ../../packages/features/views
  converter:
    path: ../../packages/features/converter
  events:
    path: ../../packages/features/events
  home_widgets:
    path: ../../packages/features/home_widgets
  firebase_analytics_app:
    path: ../../packages/features/firebase_analytics_app

  # Myanmar calendar
  flutter_mmcalendar: ^3.2.0

  # State management
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1

  # Dependency injection
  get_it: ^8.2.0
  injectable: ^2.5.2

  # Navigation
  go_router: ^16.2.4

  # Utilites
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  home_widget: ^0.8.0
  shared_preferences: ^2.5.3
  workmanager: ^0.9.0+3

  # Firebase
  firebase_core: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/google_fonts/
    - assets/images/
