name: shared_core
description: Shared core facade for common contracts and utilities.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  equatable: ^2.0.7

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.2

  # Utilities
  intl: ^0.20.0
  myanmar_calendar_dart: ^2.0.0
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  injectable_generator: ^2.9.0
