name: shared_core
description: Shared core facade for common contracts and utilities.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  equatable: ^2.1.0

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^9.2.1
  injectable: ^3.0.0

  # Utilities
  intl: ^0.20.0
  myanmar_calendar_dart: ^2.0.1
  flutter_mmcalendar: ^3.3.1
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  injectable_generator: ^3.1.3
