
name: myanmar_calendar_workspace
description: Myanmar Calendar Application Workspace
version: 2.0.0
publish_to: none
homepage: https://github.com/mixin27/mmcalendar
issue_tracker: https://github.com/mixin27/mmcalendar/issues

environment:
  sdk: ^3.11.0

# Workspace configuration
workspace:
  - packages/shared/core
  - packages/shared/ui_kit
  - packages/shared/localizations
  - packages/app_remote_config
  - packages/core
  - packages/data
  - packages/localizations
  - packages/features/calendar
  - packages/features/views
  - packages/features/converter
  - packages/features/settings
  - packages/features/notes
  - packages/features/events
  - packages/features/home_widgets
  - packages/features/firebase_analytics_app
  - apps/myanmar_calendar
  - packages/integrations/telegram_web
  - packages/integrations/database
  - packages/integrations/firebase
  - packages/features/promo
  - packages/features/holidays

# Workspace-level dependencies (shared across all packages)
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
