name: mmcalendar
description: "Simple myanmar calendar."
publish_to: "none"
version: 1.0.3+103

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  intl: ^0.19.0
  flutter_mmcalendar: ^1.1.2
  table_calendar: ^3.1.2

  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.1
  firebase_crashlytics: ^4.1.1
  firebase_remote_config: ^5.1.1
  firebase_performance: ^0.10.0+6

  easy_localization: ^3.0.7
  iconly: ^1.0.1
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3+1
  native_id: ^0.0.5
  shared_preferences: ^2.3.1
  onesignal_flutter: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.7
  auto_route_generator: ^9.0.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
