name: telegram_web
description: "Telegram Web Integration"
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
