name: integrations_firebase
description: Firebase integration package (analytics, crashlytics, remote config).
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: ../../shared/core
  firebase_core: ^4.14.0
  firebase_analytics: ^12.5.0
  firebase_crashlytics: ^5.3.0
  firebase_remote_config: ^6.6.0
  logger: ^2.6.2
  equatable: ^2.1.0
  shared_preferences: ^2.5.5
  get_it: ^9.2.1
  integrations_database:
    path: ../database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
