name: firebase_analytics_app
description: "Firebase Analytics and Crashlytics integration for Myanmar Calendar"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  integrations_firebase:
    path: ../../integrations/firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
