name: notes
description: "Notes feature"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Core packages
  core:
    path: ../../core
  data:
    path: ../../data
  firebase_analytics_app:
    path: ../firebase_analytics_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
