name: notes
description: "Notes feature"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Core packages
  shared_core:
    path: ../../shared/core
  integrations_database:
    path: ../../integrations/database
  integrations_firebase:
    path: ../../integrations/firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
