name: shared_localizations
description: Shared localization facade package.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  localizations:
    path: ../../localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
