name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Code Generation
        run: |
          # Run build_runner for all packages in the workspace that have build_runner as a dependency
          git ls-files '**/pubspec.yaml' | xargs grep -l "build_runner" | xargs -I {} dirname {} | while read dir; do
            echo "Building in $dir..."
            (cd "$dir" && dart run build_runner build --delete-conflicting-outputs)
          done

      - name: Copy firebase_options file
        run: cp apps/myanmar_calendar/lib/firebase_options.dart.example apps/myanmar_calendar/lib/firebase_options.dart

      - name: Build Web
        run: |
          cd apps/myanmar_calendar
          flutter build web --release --base-href /mmcalendar/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/myanmar_calendar/build/web
          publish_branch: gh-pages
